/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykho;

import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import BusPacket.nhaccBUS;
import BusPacket.nhanvienBUS;
import DTOPacket.nhaccDTO;
import DTOPacket.nhanvienDTO;
import login.jfmLogin;
import login.login;
import login.loginBUS;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author macintoshhd
 */
public class AdminFRM extends javax.swing.JFrame {

    /**
     * Creates new form AdminFRM
     */
    public AdminFRM() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        btntaidulieunv = new javax.swing.JButton();
        btntaidulieunv.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-process-48.png"));
        jLabel3 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTennv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiachinv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsdtnv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmailnv = new javax.swing.JTextField();
        btnthemnv = new javax.swing.JButton();
        btnthemnv.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-plus-48.png"));
        btnsuanv = new javax.swing.JButton();
        btnsuanv.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-support-48.png"));
        btnxoanv = new javax.swing.JButton();
        btnxoanv.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-delete-bin-48.png"));
        jPanel23 = new javax.swing.JPanel();
        txttimkiemnv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSNV = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdktaikhoan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdkmatkhau = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        cbbdkqh = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton1.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-signin-48.png"));
        btntaidstk = new javax.swing.JButton();
        btntaidstk.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-reset-48.png"));
        jPanel25 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbldstk = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtMancc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTenncc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDiachincc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSodtncc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEmailncc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtGhichuncc = new javax.swing.JTextField();
        btnTDLNCC = new javax.swing.JButton();
        btnThemNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btntaidulieunv.setText("Tải dữ liệu");
        btntaidulieunv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaidulieunvActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã NV");

        txtManv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManvActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên NV");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Số dt");

        jLabel7.setText("Email");

        btnthemnv.setText("Thêm");
        btnthemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemnvActionPerformed(evt);
            }
        });

        btnsuanv.setText("Sửa");
        btnsuanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuanvActionPerformed(evt);
            }
        });

        btnxoanv.setText("Xoá");
        btnxoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22Layout.setHorizontalGroup(
        	jPanel22Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel22Layout.createSequentialGroup()
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(jPanel22Layout.createSequentialGroup()
        					.addComponent(jLabel7)
        					.addGap(18)
        					.addComponent(txtEmailnv))
        				.addGroup(Alignment.LEADING, jPanel22Layout.createSequentialGroup()
        					.addGroup(jPanel22Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(jLabel5))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel22Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtTennv)
        						.addComponent(txtDiachinv)))
        				.addGroup(Alignment.LEADING, jPanel22Layout.createSequentialGroup()
        					.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(txtsdtnv))
        				.addGroup(Alignment.LEADING, jPanel22Layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(txtManv, GroupLayout.PREFERRED_SIZE, 237, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(222, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
        			.addGap(38)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btntaidulieunv, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        				.addComponent(btnthemnv, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnxoanv, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        				.addComponent(btnsuanv, GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        			.addGap(37))
        );
        jPanel22Layout.setVerticalGroup(
        	jPanel22Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel22Layout.createSequentialGroup()
        			.addGap(41)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(txtManv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(txtTennv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(txtDiachinv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(txtsdtnv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(txtEmailnv, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnsuanv)
        				.addComponent(btntaidulieunv))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel22Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnthemnv)
        				.addComponent(btnxoanv))
        			.addContainerGap(482, Short.MAX_VALUE))
        );
        jPanel22.setLayout(jPanel22Layout);

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txttimkiemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemnvActionPerformed(evt);
            }
        });
        txttimkiemnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemnvKeyReleased(evt);
            }
        });

        jLabel2.setText("Tìm kiếm");

        tblDSNV.setModel(new javax.swing.table.DefaultTableModel(

        ));
        tblDSNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSNVMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDSNV);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41)
                        .addComponent(txttimkiemnv, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttimkiemnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        JButton btnBackLogin = new JButton("Đăng xuất");
        btnBackLogin.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		AdminFRM.this.setVisible(false);
        		jfmLogin login = new jfmLogin();
        		login.setVisible(true);
        	}
        });
        
        JLabel lblNewLabel = new JLabel("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(651, Short.MAX_VALUE)
        			.addComponent(lblNewLabel)
        			.addGap(479)
        			.addComponent(btnBackLogin)
        			.addGap(46))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(27)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnBackLogin)
        				.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addGap(44))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel19);

        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        jLabel9.setText("Đăng Kí Tài Khoản");

        jLabel10.setText("Tài Khoản");

        jLabel11.setText("Mật Khẩu");

        jLabel13.setText("Quyền Hạn");

        cbbdkqh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "manager",}));

        jButton1.setText("Đăng ký");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btntaidstk.setText("Tải DSTK");
        btntaidstk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaidstkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24Layout.setHorizontalGroup(
        	jPanel24Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel24Layout.createSequentialGroup()
        			.addGap(53)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel10)
        				.addComponent(jLabel11)
        				.addComponent(jLabel13))
        			.addGap(68)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel24Layout.createSequentialGroup()
        					.addComponent(jButton1)
        					.addPreferredGap(ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        					.addComponent(btntaidstk)
        					.addGap(45))
        				.addGroup(jPanel24Layout.createSequentialGroup()
        					.addGroup(jPanel24Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtdktaikhoan, GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        						.addComponent(txtdkmatkhau)
        						.addComponent(cbbdkqh, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addContainerGap(88, Short.MAX_VALUE))))
        );
        jPanel24Layout.setVerticalGroup(
        	jPanel24Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel24Layout.createSequentialGroup()
        			.addGap(19)
        			.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel10)
        				.addComponent(txtdktaikhoan, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel11)
        				.addComponent(txtdkmatkhau, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cbbdkqh, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(jPanel24Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(btntaidstk))
        			.addContainerGap(604, Short.MAX_VALUE))
        );
        jPanel24.setLayout(jPanel24Layout);

        jPanel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbldstk.setModel(new javax.swing.table.DefaultTableModel(
        ));
        tbldstk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldstkMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbldstk);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel8.setText("Quản Lý Tài Khoản");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21Layout.setHorizontalGroup(
        	jPanel21Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel21Layout.createSequentialGroup()
        			.addGap(447)
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 217, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(764, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, jPanel21Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel24, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
        			.addComponent(jPanel25, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        jPanel21Layout.setVerticalGroup(
        	jPanel21Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel21Layout.createSequentialGroup()
        			.addContainerGap(59, Short.MAX_VALUE)
        			.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel25, 0, 0, Short.MAX_VALUE)
        				.addComponent(jPanel24, GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
        			.addGap(162))
        );
        jPanel21.setLayout(jPanel21Layout);

        jTabbedPane1.addTab("Tài Khoản", jPanel21);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel19.setText("Nhà Cung Cấp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(531, 531, 531)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Mã nhà cung cấp:");

        jLabel14.setText("Tên nhà cung cấp:");

        jLabel15.setText("Địa Chỉ:");

        jLabel16.setText("Số điện thoại");

        txtSodtncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSodtnccActionPerformed(evt);
            }
        });

        jLabel17.setText("Email");

        jLabel18.setText("Ghi chú");

        btnTDLNCC.setText("Tải Dữ Liệu");
        btnTDLNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTDLNCCActionPerformed(evt);
            }
        });

        btnThemNCC.setText("Thêm");
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnSuaNCC.setText("Sửa");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setText("Xoá");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenncc))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(23, 23, 23)
                        .addComponent(txtMancc))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSodtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiachincc, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailncc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnThemNCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaNCC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaNCC))
                            .addComponent(txtGhichuncc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnTDLNCC)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTenncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDiachincc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSodtncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEmailncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtGhichuncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTDLNCC)
                    .addComponent(btnThemNCC)
                    .addComponent(btnSuaNCC)
                    .addComponent(btnXoaNCC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
        ));
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNCC);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhà Cung Cấp", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntaidulieunvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaidulieunvActionPerformed
        nhanvienBUS dsnv = new nhanvienBUS();
        try{
            dsnv.docnv();
        }catch(Exception e)
        {

        }
        Vector header = new Vector();
        header.add("Mã nhân viên");
        header.add("Tên nhân viên");
        header.add("Địa chỉ");
        header.add("Số điện thoại");
        header.add("Email");
        DefaultTableModel model= new DefaultTableModel(header,0){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;

            }
        };
        for(nhanvienDTO nv : nhanvienBUS.dsnv){
            Vector row = new Vector();
            row.add(nv.getManv());
            row.add(nv.getTennv());
            row.add(nv.getDiachi());
            row.add(nv.getSdt());
            row.add(nv.getEmail());
            model.addRow(row);
        }
        tblDSNV.setModel(model);
    }//GEN-LAST:event_btntaidulieunvActionPerformed

    private void txtManvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManvActionPerformed

    private void btnthemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemnvActionPerformed
        if(txtManv.getText()!=""){
            nhanvienDTO nv = new nhanvienDTO();
            nv.setManv(txtManv.getText());
            nv.setTennv(txtTennv.getText());
            nv.setDiachi(txtDiachinv.getText());
            nv.setSdt(txtsdtnv.getText());
            nv.setEmail(txtEmailnv.getText());
            nhanvienBUS dsnv = new nhanvienBUS();
            String error = dsnv.kiemtratrunglap(nv);
            if(!"".equals(error)){
                CustomMessage.ErrorPanel(error);
            }else{
                try{
                    dsnv.themNV(nv);
                    this.btntaidulieunvActionPerformed(evt);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "khong vao duoc");
                }
            }
            txtManv.setText("");
            txtTennv.setText("");
            txtDiachinv.setText("");
            txtsdtnv.setText("");
            txtEmailnv.setText("");
        }
    }//GEN-LAST:event_btnthemnvActionPerformed

    private void btnsuanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuanvActionPerformed
        if(txtManv.getText()!=""){
            nhanvienDTO nv = new nhanvienDTO();
            int i = tblDSNV.getSelectedRow();
            String Manvcu = (String)tblDSNV.getModel().getValueAt(i, 0);
            nv.setManv(txtManv.getText());
            nv.setTennv(txtTennv.getText());
            nv.setDiachi(txtDiachinv.getText());
            nv.setSdt(txtsdtnv.getText());
            nv.setEmail(txtEmailnv.getText());
            nhanvienBUS dsnv = new nhanvienBUS();
            String error = dsnv.kiemtrahople(nv, Manvcu);
            if(error.equals("")){
                try{
                    dsnv.suaNV(nv);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "khong sua duoc");
                }

            }else{
                CustomMessage.ErrorPanel(error);
            }
            this.btntaidulieunvActionPerformed(evt);
        }
    }//GEN-LAST:event_btnsuanvActionPerformed

    private void btnxoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanvActionPerformed
        if(txtManv.getText()!=""){
            nhanvienDTO nv = new nhanvienDTO();
            nv.setManv(txtManv.getText());
            nv.setTennv(txtTennv.getText());
            nv.setDiachi(txtDiachinv.getText());
            nv.setSdt(txtsdtnv.getText());
            nv.setEmail(txtEmailnv.getText());
            nhanvienBUS dsnv = new nhanvienBUS();
            if(dsnv.kiemtratontai(nv)){
                try{
                    dsnv.xoaNV(nv);
                }catch(Exception e){

                }
            }else{
                CustomMessage.ErrorPanel("Nhan Vien khong ton tai");
            }
            this.btntaidulieunvActionPerformed(evt);
        }
    }//GEN-LAST:event_btnxoanvActionPerformed

    private void txttimkiemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemnvActionPerformed

    }//GEN-LAST:event_txttimkiemnvActionPerformed

    private void txttimkiemnvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemnvKeyReleased
        int i = tblDSNV.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel)tblDSNV.getModel();
        String td = txttimkiemnv.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel>(table);
        tblDSNV.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(td));
    }//GEN-LAST:event_txttimkiemnvKeyReleased

    private void tblDSNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSNVMouseClicked
        int i = tblDSNV.getSelectedRow();
        txtManv.setText(tblDSNV.getModel().getValueAt(i, 0).toString());
        txtTennv.setText(tblDSNV.getModel().getValueAt(i, 1).toString());
        txtDiachinv.setText(tblDSNV.getModel().getValueAt(i, 2).toString());
        txtsdtnv.setText(tblDSNV.getModel().getValueAt(i, 3).toString());
        txtEmailnv.setText(tblDSNV.getModel().getValueAt(i, 4).toString());

    }//GEN-LAST:event_tblDSNVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtdktaikhoan.getText()!=""||String.valueOf(txtdkmatkhau.getPassword())!=""){
            login lg = new login();
            lg.setTaikhoan(txtdktaikhoan.getText());
            lg.setMatkhau(String.valueOf(txtdkmatkhau.getPassword()));
            lg.setPhanquyen((String) cbbdkqh.getSelectedItem());
            loginBUS dsdn = new loginBUS();
            String error = dsdn.kiemtratrunglap(lg);
                        if(!"".equals(error)){
                CustomMessage.ErrorPanel(error);
            }else{
                try{
                    dsdn.themlogin(lg);
                    this.btntaidstkActionPerformed(evt);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "them tk k duoc");
                }
            }
            txtdktaikhoan.setText("");
            txtdkmatkhau.setText("");
            cbbdkqh.setSelectedItem("admin");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btntaidstkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaidstkActionPerformed
        loginBUS dsdn = new loginBUS();
        try{
            dsdn.docdsdn();
        }catch(Exception e){

        }
        Vector header = new Vector();
        header.add("taikhoan");
        header.add("matkhau");
        header.add("phanquyen");
        DefaultTableModel model = new DefaultTableModel(header,0){
            @Override
            public boolean isCellEditable(int row,int comlumn){
                return false;
            }
        };
        for(login lg : loginBUS.dsdn){
            Vector row = new Vector();
            row.add(lg.getTaikhoan());
            row.add(lg.getMatkhau());
            row.add(lg.getPhanquyen());
            model.addRow(row);
        }
        tbldstk.setModel(model);
    }//GEN-LAST:event_btntaidstkActionPerformed

    private void tbldstkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldstkMouseClicked
        int i = tbldstk.getSelectedRow();
        txtdktaikhoan.setText(tbldstk.getModel().getValueAt(i, 0).toString());
        txtdkmatkhau.setText(tbldstk.getModel().getValueAt(i, 1).toString());

        cbbdkqh.setSelectedItem(tbldstk.getModel().getValueAt(i, 2).toString());
    }//GEN-LAST:event_tbldstkMouseClicked

    private void txtSodtnccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSodtnccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodtnccActionPerformed

    private void btnTDLNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTDLNCCActionPerformed
            nhaccBUS dsncc = new nhaccBUS();
            try{
                dsncc.docNCC();
            }catch(Exception e){
                
            }
            Vector header = new Vector();
            header.add("MaNCC");
            header.add("TenNCC");
            header.add("Diachi");
            header.add("Sodt");
            header.add("Email");
            header.add("Noidung");
            DefaultTableModel model = new DefaultTableModel(header, 0){
                @Override
                public boolean isCellEditable(int row,int Column){
                    return false;
                }
            };
            for(nhaccDTO ncc : nhaccBUS.dsncc){
                Vector row = new Vector();
                row.add(ncc.getMancc());
                row.add(ncc.getTenncc());
                row.add(ncc.getDiachincc());
                row.add(ncc.getSdtncc());
                row.add(ncc.getEmailncc());
                row.add(ncc.getNoidung());
                model.addRow(row);
    }
            tblNCC.setModel(model);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTDLNCCActionPerformed

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
            int count  =tblNCC.getSelectedRowCount();
            if(count!=0&&txtMancc.getText()!=""){
                nhaccBUS dsncc = new nhaccBUS();
                nhaccDTO ncc = new nhaccDTO();
                ncc.setMancc(txtMancc.getText());
                ncc.setTenncc(txtTenncc.getText());
                ncc.setDiachincc(txtDiachincc.getText());
                ncc.setSdtncc(txtSodtncc.getText());
                ncc.setEmailncc(txtEmailncc.getText());
                ncc.setNoidung(txtGhichuncc.getText());
                String error = dsncc.Kiemtratrunglap(ncc);
                if(!"".equals(error)){
                    
                }else{
                    try{
                        dsncc.ThemNCC(ncc);
                        this.btnTDLNCCActionPerformed(evt);
                    }catch(Exception e){
                        
                    }
                }
            }
            txtMancc.setText("");
            txtTenncc.setText("");
            txtDiachincc.setText("");
            txtSodtncc.setText("");
            txtEmailncc.setText("");
            txtGhichuncc.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
         if(txtMancc.getText()!=""){
                nhaccBUS dsncc = new nhaccBUS();
                nhaccDTO ncc = new nhaccDTO();
                int i = tblNCC.getSelectedRowCount();
                String MaKhoCu = tblNCC.getModel().getValueAt(i, 0).toString();
                ncc.setMancc(txtMancc.getText());
                ncc.setTenncc(txtTenncc.getText());
                ncc.setDiachincc(txtDiachincc.getText());
                ncc.setSdtncc(txtSodtncc.getText());
                ncc.setEmailncc(txtEmailncc.getText());
                ncc.setNoidung(txtGhichuncc.getText());
                String error = dsncc.KiemtraHople(ncc, MaKhoCu);
                if(error.equals("")){
                    try{
                    dsncc.SuaNCC(ncc);
                    }catch(Exception e){
                        
                    }
                }else{
                                    }
                this.btnTDLNCCActionPerformed(evt);
            }
            txtMancc.setText("");
            txtTenncc.setText("");
            txtDiachincc.setText("");
            txtSodtncc.setText("");
            txtEmailncc.setText("");

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
            int i = tblNCC.getSelectedRow();
            txtMancc.setText(tblNCC.getModel().getValueAt(i, 0).toString());
            txtTenncc.setText(tblNCC.getModel().getValueAt(i, 1).toString());
            txtDiachincc.setText(tblNCC.getModel().getValueAt(i, 2).toString());
            txtSodtncc.setText(tblNCC.getModel().getValueAt(i, 3).toString());
            txtEmailncc.setText(tblNCC.getModel().getValueAt(i, 4).toString());
            txtGhichuncc.setText(tblNCC.getModel().getValueAt(i, 5).toString());

                        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tblNCCMouseClicked

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        if(txtMancc.getText()!=""){
                nhaccBUS dsncc = new nhaccBUS();
                nhaccDTO ncc = new nhaccDTO();
                
                ncc.setMancc(txtMancc.getText());
                ncc.setTenncc(txtTenncc.getText());
                ncc.setDiachincc(txtDiachincc.getText());
                ncc.setSdtncc(txtSodtncc.getText());
                ncc.setEmailncc(txtEmailncc.getText());
                ncc.setNoidung(txtGhichuncc.getText());
               
                
                if(dsncc.KiemtraTontai(ncc)){
                    try{
                    dsncc.XoaNCC(ncc);
                    }catch(Exception e){
                        
                    }
                }else{
                                    }
                this.btnTDLNCCActionPerformed(evt);

                        }
         txtMancc.setText("");
            txtTenncc.setText("");
            txtDiachincc.setText("");
            txtSodtncc.setText("");
            txtEmailncc.setText("");
            txtGhichuncc.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnTDLNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JButton btnsuanv;
    private javax.swing.JButton btntaidstk;
    private javax.swing.JButton btntaidulieunv;
    private javax.swing.JButton btnthemnv;
    private javax.swing.JButton btnxoanv;
    private javax.swing.JComboBox<String> cbbdkqh;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDSNV;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTable tbldstk;
    private javax.swing.JTextField txtDiachincc;
    private javax.swing.JTextField txtDiachinv;
    private javax.swing.JTextField txtEmailncc;
    private javax.swing.JTextField txtEmailnv;
    private javax.swing.JTextField txtGhichuncc;
    private javax.swing.JTextField txtMancc;
    private javax.swing.JTextField txtManv;
    private javax.swing.JTextField txtSodtncc;
    private javax.swing.JTextField txtTenncc;
    private javax.swing.JTextField txtTennv;
    private javax.swing.JPasswordField txtdkmatkhau;
    private javax.swing.JTextField txtdktaikhoan;
    private javax.swing.JTextField txtsdtnv;
    private javax.swing.JTextField txttimkiemnv;
}
