/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.sql.*;
import javax.swing.*;
import login.*;
import java.util.ArrayList;
import quanlykho.AdminFRM;
import quanlykho.KhoFRM;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author macintoshhd
 */
public class jfmLogin extends javax.swing.JFrame {
        
    /**
     * Creates new form jfmLogin
     */
    public jfmLogin() {
        initComponents();
                this.lbconnect.setText(Checklogin.testConnect());

        
           }
public static ResultSet rs =null;
public static PreparedStatement pst = null;
public static String manv;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnDN = new javax.swing.JButton();
        btnNL = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbconnect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tài Khoản");

        jLabel2.setText("Mật Khẩu");

        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        btnDN.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-signin-48.png")); // NOI18N
        btnDN.setText("Dang Nhap");
        btnDN.setLocation(new java.awt.Point(60, 60));
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });

        btnNL.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-reset-48.png")); // NOI18N
        btnNL.setText("Nhap Lai");
        btnNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNLActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new ImageIcon("/Users/tranthanhtung/Desktop/untitled folder/CHAU/src/image&icon/icons8-exit-48.png")); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setText("Đăng Nhập Tài Khoản");

        lbconnect.setText("tinh trang ket noi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(209, Short.MAX_VALUE)
        			.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 288, GroupLayout.PREFERRED_SIZE)
        			.addGap(154))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(91)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jLabel2))
        			.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(txtpassword)
        				.addComponent(txtuser, GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        			.addGap(171))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(85)
        			.addComponent(btnDN, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        			.addGap(32)
        			.addComponent(btnNL, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        			.addGap(53)
        			.addComponent(btnThoat, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(91, Short.MAX_VALUE))
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addGap(236)
        			.addComponent(lbconnect)
        			.addContainerGap(237, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(8)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtuser, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtpassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(52)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnDN, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(btnThoat, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNL))
        			.addGap(57)
        			.addComponent(lbconnect)
        			.addGap(81))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
       loginBUS bus = new loginBUS();
        try{
            bus.docdsdn();
        }catch(Exception e){
        }
       for(login lg : loginBUS.dsdn){ 
        if(this.txtuser.getText().length()==0 || String.valueOf(this.txtpassword.getPassword()).length()==0)
       {
           JOptionPane.showMessageDialog(null, "Ban Chua Nhap Thong Tin");
       }
       else{
           rs = Checklogin.clog(this.txtuser.getText(), String.valueOf(this.txtpassword.getPassword()));           
                   try {
                       if(rs.next()){
                           if(rs.getString(3).toString().equals("admin")){
                               AdminFRM ad = new AdminFRM();
                               ad.setVisible(true);
                               jfmLogin.this.setVisible(false);
                               break;
                           }else{
                               KhoFRM kho = new  KhoFRM();
                               kho.setVisible(true);
                               jfmLogin.this.setVisible(false);
                               break;
                           }
                       
                       }
                   }
                    catch(Exception e){
                          }
           
                   
        }
       }

// TODO add your handling code here:
    }//GEN-LAST:event_btnDNActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void btnNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNLActionPerformed
                this.txtuser.setText(null);
                this.txtpassword.setText(null);
               


        // TODO add your handling code here:
    }//GEN-LAST:event_btnNLActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed

                System.exit(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed
       /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JButton btnNL;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbconnect;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
